### ISSUE TITLE
text.replace is not a function

### ISSUE THREAD

**Issue by joelworsham** [rasmusbe/gulp-wp-pot#39]
Full Log:

```
[12:46:31] Starting 'generate_pot'...
/Users/joelworsham/Sites/www/wordpress-develop/public_html/src/wp-content/plugins/learndash-gradebook/node_modules/wp-pot/index.js:361
  text = text.replace(/\\([\s\S])|(")/g, '\\$1$2');
              ^

TypeError: text.replace is not a function
    at escapeQuotes (/Users/joelworsham/Sites/www/wordpress-develop/public_html/src/wp-content/plugins/learndash-gradebook/node_modules/wp-pot/index.js:361:15)
    at getPotMsgId (/Users/joelworsham/Sites/www/wordpress-develop/public_html/src/wp-content/plugins/learndash-gradebook/node_modules/wp-pot/index.js:378:13)
    at translationToPot (/Users/joelworsham/Sites/www/wordpress-develop/public_html/src/wp-content/plugins/learndash-gradebook/node_modules/wp-pot/index.js:434:32)
    at generatePot (/Users/joelworsham/Sites/www/wordpress-develop/public_html/src/wp-content/plugins/learndash-gradebook/node_modules/wp-pot/index.js:475:28)
    at wpPot (/Users/joelworsham/Sites/www/wordpress-develop/public_html/src/wp-content/plugins/learndash-gradebook/node_modules/wp-pot/index.js:514:23)
    at DestroyableTransform._flush (/Users/joelworsham/Sites/www/wordpress-develop/public_html/src/wp-content/plugins/learndash-gradebook/node_modules/gulp-wp-pot/index.js:51:25)
    at DestroyableTransform.<anonymous> (/Users/joelworsham/Sites/www/wordpress-develop/public_html/src/wp-content/plugins/learndash-gradebook/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)

Process finished with exit code 1
```

**Comment by joelworsham** [comment]
Issue was on my end. I was interpolating a var into the string to be translated, rather than using `sprintf()`.
