### ISSUE TITLE
Parse errors throw exception instead of emitting error

### ISSUE THREAD

**Issue by stefanfisk** [rasmusbe/gulp-wp-pot#60]
I am using `gulp-wp-pot` in a watch task, but the task crashes when wp-pot fails to parse a file.

```
[09:31:51] Starting 'pot'...
/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/wp-pot/translation-parser.js:325
        throw e;
        ^

SyntaxError: Parse Error : syntax error, expecting T_ENDIF on line 530 | Unable to parse page-application.php
    at parser.raiseError (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/php-parser/src/parser.js:261:15)
    at parser.error (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/php-parser/src/parser.js:301:15)
    at parser.expect (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/php-parser/src/parser.js:386:10)
    at parser.read_if (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/php-parser/src/parser/if.js:39:12)
    at parser.read_statement (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/php-parser/src/parser/statement.js:194:46)
    at parser.read_top_statement (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/php-parser/src/parser/statement.js:74:21)
    at parser.read_start (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/php-parser/src/parser/main.js:17:19)
    at parser.parse (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/php-parser/src/parser.js:243:21)
    at engine.parseCode (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/php-parser/src/index.js:168:22)
    at TranslationParser.parseFile (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/wp-pot/translation-parser.js:321:28)
```

**Comment by theenoahmason** [comment]
@stefanfisk I can confirm issue with gulp 4.0.0 and gulp-wp-pot 2.0.7. This plugin has to allow for the following syntax:

**Comment by rasmusbe** [comment]
Could you please try with the prerelease 2.2.0-0

**Comment by stefanfisk** [comment]
I'm afraid that just changed the error being thrown.

If I understand the stack trace correctly `php-parser` is throwing this outside of any gulp related code, so maybe there's no appropriate try / catch to turn the exception into a stream error?

**Comment by stefanfisk** [comment]
TIL about the 10 line limit when node prints stack traces...

This is what I get after the change you made:

```
/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/gulp-wp-pot/index.js:58
      throw new PluginError('gulp-wp-pot', error);
      ^
SyntaxError: Parse Error : syntax error, unexpected 'html' (T_STRING), expecting ')' on line 2 | Unable to parse email.php
    at parser.raiseError (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/php-parser/src/parser.js:261:15)
    at parser.error (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/php-parser/src/parser.js:301:15)
    at parser.expect (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/php-parser/src/parser.js:386:10)
    at parser.read_function_argument_list (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/php-parser/src/parser/function.js:211:10)
    at parser.recursive_variable_chain_scan (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/php-parser/src/parser/variable.js:108:29)
    at parser.read_variable (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/php-parser/src/parser/variable.js:69:17)
    at parser.read_expr_item (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/php-parser/src/parser/expr.js:353:19)
    at parser.read_expr (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/php-parser/src/parser/expr.js:12:21)
    at parser.read_list (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/php-parser/src/parser/utils.js:42:26)
    at parser.read_statement (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/php-parser/src/parser/statement.js:256:32)
    at parser.read_top_statement (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/php-parser/src/parser/statement.js:74:21)
    at parser.read_start (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/php-parser/src/parser/main.js:17:19)
    at parser.parse (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/php-parser/src/parser.js:243:21)
    at engine.parseCode (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/php-parser/src/index.js:168:22)
    at TranslationParser.parseFile (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/wp-pot/translation-parser.js:321:28)
    at wpPot (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/wp-pot/index.js:171:38)
    at DestroyableTransform._flush (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/gulp-wp-pot/index.js:51:27)
    at DestroyableTransform.<anonymous> (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/readable-stream/lib/_stream_transform.js:138:49)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at DestroyableTransform.emit (events.js:208:7)
    at prefinish (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/readable-stream/lib/_stream_writable.js:596:14)
    at finishMaybe (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/readable-stream/lib/_stream_writable.js:604:5)
    at endWritable (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/readable-stream/lib/_stream_writable.js:615:3)
    at DestroyableTransform.Writable.end (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/readable-stream/lib/_stream_writable.js:571:41)
    at DestroyableTransform.onend (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/readable-stream/lib/_stream_readable.js:570:10)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at DestroyableTransform.emit (events.js:208:7)
    at endReadableNT (/Users/stefanfisk/Projects/berghs/berghs.se/repo/node_modules/readable-stream/lib/_stream_readable.js:992:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by rasmusbe** [comment]
Could you give me an example of some php code that makes php-parser break?

**Comment by stefanfisk** [comment]
A file containing only `<?= __('` will do the trick.

**Comment by stefanfisk** [comment]
I've never written a Gulp plugin, but maybe you should use `this.emit()`  instead of `throw`? https://github.com/gulpjs/gulp/tree/master/docs/writing-a-plugin

**Comment by stefanfisk** [comment]
Now the error seems to be handled properly!

**Comment by rasmusbe** [comment]
Great, thanks for your help!
I have released 2.2.0 now with better error handling.

**Comment by theenoahmason** [comment]
@rasmusbe @stefanfisk I can confirm 2.2.0 Does the trick! Thank you again!

It is worth noting in your README.md for `gulp-wp-pot` that errors should be handled with a minimum of this:

**Comment by daviedR** [comment]
@theenoahmason @stefanfisk @rasmusbe 

I use `gulp-watch` plugin to instead of the native `watch` task. When php parsing fails, the watch task stops working. I tried the snippet from @theenoahmason but no luck, the watch task still stops working.
