### ISSUE TITLE
Unable to parse php file

### ISSUE THREAD

**Issue by bondansebastian** [rasmusbe/gulp-wp-pot#78]
Hi @rasmusbe ,
Thanks for this cool plugin

Unfortunately i'm currently facing an issue with this plugin.
Whenever i run the gulp task, this error always shows up
`TypeError: Cannot read property 'toLowerCase' of undefined | Unable to parse inc/class-tgm-plugin-activation.php`

I'm using version `^2.3.2` of `gulp-wp-pot`
`npm` version `6.2.0`
`gulp` CLI version `2.0.1`, Local version `3.9.1`

Here's the full error log
```
throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'toLowerCase' of undefined | Unable to parse inc/class-tgm-plugin-activation.php
    at parser.read_variable (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\variable.js:48:35)
    at parser.read_expr_item (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\expr.js:342:19)
    at parser.read_expr (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\expr.js:11:23)
    at parser.read_expr (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\expr.js:67:60)
    at parser.read_expr_item (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\expr.js:130:26)
    at parser.read_expr (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\expr.js:11:23)
    at parser.read_expr_item (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\expr.js:110:50)
    at parser.read_expr (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\expr.js:11:23)
    at parser.read_expr (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\expr.js:43:52)
    at parser.read_expr_item (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\expr.js:110:50)
    at parser.read_expr (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\expr.js:11:23)
    at parser.read_if_expr (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\if.js:57:25)
    at parser.read_if (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\if.js:22:24)
    at parser.read_statement (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\statement.js:201:21)
    at parser.read_inner_statement (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\statement.js:188:21)
    at parser.read_inner_statements (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\statement.js:88:30)
    at parser.read_code_block (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\statement.js:400:14)
    at parser.read_function (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\function.js:48:28)
    at parser.read_class_body (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\class.js:103:26)
    at parser.read_class (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\class.js:29:30)
    at parser.read_inner_statement (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\statement.js:170:21)
    at parser.read_inner_statements (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\statement.js:88:30)
    at parser.read_code_block (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\statement.js:400:14)
    at parser.read_statement (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\statement.js:198:21)
    at parser.read_if (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\if.js:43:19)
    at parser.read_statement (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\statement.js:201:21)
    at parser.read_top_statement (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\statement.js:76:21)
    at parser.read_start (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser\main.js:18:19)
    at parser.parse (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\parser.js:276:23)
    at engine.parseCode (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\node_modules\php-parser\src\index.js:167:22)
    at TranslationParser.parseFile (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\translation-parser.js:346:28)
    at wpPot (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\wp-pot\index.js:171:38)
    at DestroyableTransform._flush (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\gulp-wp-pot\index.js:51:27)
    at DestroyableTransform.prefinish (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\readable-stream\lib\_stream_transform.js:138:10)
    at emitNone (events.js:106:13)
    at DestroyableTransform.emit (events.js:208:7)
    at prefinish (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\readable-stream\lib\_stream_writable.js:619:14)
    at finishMaybe (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\readable-stream\lib\_stream_writable.js:627:5)
    at endWritable (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\readable-stream\lib\_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\readable-stream\lib\_stream_writable.js:594:41)
    at DestroyableTransform.onend (C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:523:10)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at DestroyableTransform.emit (events.js:208:7)
    at C:\DevProjects\wordpress-fresh\wp-content\themes\toba\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:965:16
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Finally, here's my gulp task
```
gulp.task( 'pot', function() {
    return gulp.src( './**/*.php' )
        .pipe( wpPot({
            domain: 'toba',
            package: 'Toba Theme'
        }) )
        .pipe( gulp.dest( './languages/toba.pot' ) );
});
```

**Comment by rasmusbe** [comment]
Hi,

Could you give me the contents of `inc/class-tgm-plugin-activation.php` so I can debug?

/Rasmus

**Comment by rasmusbe** [comment]
The bug was a problem in the php-parser dependency, but it's already fixed. I have released a new version of gulp-wp-pot with a never version of the php-parser.
